#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Customers.Droid.Resource", IsApplication=true)]

namespace Customers.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::iFactr.Droid.Resource.Color.HeaderColor = global::Customers.Droid.Resource.Color.HeaderColor;
			global::iFactr.Droid.Resource.Color.HeaderTextColor = global::Customers.Droid.Resource.Color.HeaderTextColor;
			global::iFactr.Droid.Resource.Color.LayerBackgroundColor = global::Customers.Droid.Resource.Color.LayerBackgroundColor;
			global::iFactr.Droid.Resource.Color.LayerItemBackgroundColor = global::Customers.Droid.Resource.Color.LayerItemBackgroundColor;
			global::iFactr.Droid.Resource.Color.SecondarySubTextColor = global::Customers.Droid.Resource.Color.SecondarySubTextColor;
			global::iFactr.Droid.Resource.Color.SectionHeaderColor = global::Customers.Droid.Resource.Color.SectionHeaderColor;
			global::iFactr.Droid.Resource.Color.SectionHeaderTextColor = global::Customers.Droid.Resource.Color.SectionHeaderTextColor;
			global::iFactr.Droid.Resource.Color.SelectionColor = global::Customers.Droid.Resource.Color.SelectionColor;
			global::iFactr.Droid.Resource.Color.SeparatorColor = global::Customers.Droid.Resource.Color.SeparatorColor;
			global::iFactr.Droid.Resource.Color.SubTextColor = global::Customers.Droid.Resource.Color.SubTextColor;
			global::iFactr.Droid.Resource.Color.TextColor = global::Customers.Droid.Resource.Color.TextColor;
			global::iFactr.Droid.Resource.Dimension.BottomMargin = global::Customers.Droid.Resource.Dimension.BottomMargin;
			global::iFactr.Droid.Resource.Dimension.CellHeight = global::Customers.Droid.Resource.Dimension.CellHeight;
			global::iFactr.Droid.Resource.Dimension.LargeHorizontalSpacing = global::Customers.Droid.Resource.Dimension.LargeHorizontalSpacing;
			global::iFactr.Droid.Resource.Dimension.LargeVerticalSpacing = global::Customers.Droid.Resource.Dimension.LargeVerticalSpacing;
			global::iFactr.Droid.Resource.Dimension.LeftMargin = global::Customers.Droid.Resource.Dimension.LeftMargin;
			global::iFactr.Droid.Resource.Dimension.RightMargin = global::Customers.Droid.Resource.Dimension.RightMargin;
			global::iFactr.Droid.Resource.Dimension.SmallHorizontalSpacing = global::Customers.Droid.Resource.Dimension.SmallHorizontalSpacing;
			global::iFactr.Droid.Resource.Dimension.SmallVerticalSpacing = global::Customers.Droid.Resource.Dimension.SmallVerticalSpacing;
			global::iFactr.Droid.Resource.Dimension.TopMargin = global::Customers.Droid.Resource.Dimension.TopMargin;
			global::iFactr.Droid.Resource.Drawable.ic_accessory = global::Customers.Droid.Resource.Drawable.ic_accessory;
			global::iFactr.Droid.Resource.Drawable.ic_menu_dark = global::Customers.Droid.Resource.Drawable.ic_menu_dark;
			global::iFactr.Droid.Resource.Drawable.ic_menu_light = global::Customers.Droid.Resource.Drawable.ic_menu_light;
			global::iFactr.Droid.Resource.Drawable.ic_menu_more_dark = global::Customers.Droid.Resource.Drawable.ic_menu_more_dark;
			global::iFactr.Droid.Resource.Drawable.ic_menu_more_light = global::Customers.Droid.Resource.Drawable.ic_menu_more_light;
			global::iFactr.Droid.Resource.Id.ab_basemaps_subtitle = global::Customers.Droid.Resource.Id.ab_basemaps_subtitle;
			global::iFactr.Droid.Resource.Id.ab_basemaps_title = global::Customers.Droid.Resource.Id.ab_basemaps_title;
			global::iFactr.Droid.Resource.Id.action = global::Customers.Droid.Resource.Id.action;
			global::iFactr.Droid.Resource.Id.detail_background = global::Customers.Droid.Resource.Id.detail_background;
			global::iFactr.Droid.Resource.Id.detail_fragment = global::Customers.Droid.Resource.Id.detail_fragment;
			global::iFactr.Droid.Resource.Id.fullscreen_fragment = global::Customers.Droid.Resource.Id.fullscreen_fragment;
			global::iFactr.Droid.Resource.Id.headerBackground = global::Customers.Droid.Resource.Id.headerBackground;
			global::iFactr.Droid.Resource.Id.home = global::Customers.Droid.Resource.Id.home;
			global::iFactr.Droid.Resource.Id.master_background = global::Customers.Droid.Resource.Id.master_background;
			global::iFactr.Droid.Resource.Id.master_fragment = global::Customers.Droid.Resource.Id.master_fragment;
			global::iFactr.Droid.Resource.Id.options = global::Customers.Droid.Resource.Id.options;
			global::iFactr.Droid.Resource.Id.popover_background = global::Customers.Droid.Resource.Id.popover_background;
			global::iFactr.Droid.Resource.Id.popover_fragment = global::Customers.Droid.Resource.Id.popover_fragment;
			global::iFactr.Droid.Resource.Id.title = global::Customers.Droid.Resource.Id.title;
			global::iFactr.Droid.Resource.Layout.ab_main_view = global::Customers.Droid.Resource.Layout.ab_main_view;
			global::iFactr.Droid.Resource.Layout.fullscreen = global::Customers.Droid.Resource.Layout.fullscreen;
			global::iFactr.Droid.Resource.Layout.main = global::Customers.Droid.Resource.Layout.main;
			global::iFactr.Droid.Resource.Layout.popover = global::Customers.Droid.Resource.Layout.popover;
			global::iFactr.Droid.Resource.Layout.popover_fullscreen = global::Customers.Droid.Resource.Layout.popover_fullscreen;
			global::iFactr.Droid.Resource.Style.rating = global::Customers.Droid.Resource.Style.rating;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int HeaderColor = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int HeaderTextColor = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int LayerBackgroundColor = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int LayerItemBackgroundColor = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int SecondarySubTextColor = 2130968586;
			
			// aapt resource value: 0x7f040002
			public const int SectionHeaderColor = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int SectionHeaderTextColor = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int SelectionColor = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int SeparatorColor = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int SubTextColor = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int TextColor = 2130968584;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050004
			public const int BottomMargin = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int CellHeight = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int LargeHorizontalSpacing = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int LargeVerticalSpacing = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int LeftMargin = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int RightMargin = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int SmallHorizontalSpacing = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int SmallVerticalSpacing = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int TopMargin = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_accessory = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_menu_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_menu_light = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_menu_more_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_menu_more_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon_launcher = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080001
			public const int ab_basemaps_subtitle = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int ab_basemaps_title = 2131230720;
			
			// aapt resource value: 0x7f08000a
			public const int action = 2131230730;
			
			// aapt resource value: 0x7f080006
			public const int detail_background = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int detail_fragment = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int fullscreen_fragment = 2131230722;
			
			// aapt resource value: 0x7f080007
			public const int headerBackground = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int home = 2131230728;
			
			// aapt resource value: 0x7f080003
			public const int master_background = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int master_fragment = 2131230724;
			
			// aapt resource value: 0x7f08000b
			public const int options = 2131230731;
			
			// aapt resource value: 0x7f08000d
			public const int popover_background = 2131230733;
			
			// aapt resource value: 0x7f08000c
			public const int popover_fragment = 2131230732;
			
			// aapt resource value: 0x7f080009
			public const int title = 2131230729;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ab_main_view = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fullscreen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int popover = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int popover_fullscreen = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int rating = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
